#!/bin/bash
# =============================================================================
# generate_baseline.sh
# Purpose : Creates the initial baseline of critical file hashes and permissions
#           This script must be run ONCE on first deployment (via install.sh)
#           On every subsequent run, file_integrity.sh compares against this file
# Usage   : sudo bash generate_baseline.sh
# Output  : data/file_baseline.db
# =============================================================================

# -----------------------------------------------------------------------------
# CONFIGURATION
# Where the baseline file will be stored
# -----------------------------------------------------------------------------
BASELINE_FILE="$(dirname "$0")/data/file_baseline.db"
LOG_FILE="$(dirname "$0")/logs/alerts.log"

# -----------------------------------------------------------------------------
# LIST OF CRITICAL FILES TO MONITOR
# These are the files whose unexpected modification should trigger an alert
# Covers: identity, authentication, persistence, SSH, and PAM
# -----------------------------------------------------------------------------
CRITICAL_FILES=(
    /etc/passwd
    /etc/shadow
    /etc/group
    /etc/gshadow
    /etc/sudoers
    /etc/ssh/sshd_config
    /etc/pam.d/common-auth
    /etc/pam.d/sshd
    /etc/crontab
    /etc/hostname
    /etc/hosts
    /root/.ssh/authorized_keys
)

# -----------------------------------------------------------------------------
# HELPER: timestamp
# Returns the current date/time in ISO 8601 format for log entries
# -----------------------------------------------------------------------------
timestamp() {
    date +"%Y-%m-%dT%H:%M:%S"
}

# -----------------------------------------------------------------------------
# HELPER: log_message
# Placeholder for the alerting.sh integration
# When alerting.sh is ready, replace the echo below with: alert "INFO" "file_integrity" "$1"
# -----------------------------------------------------------------------------
log_message() {
    local level="$1"
    local message="$2"
    echo "$(timestamp) $level file_integrity $message" | tee -a "$LOG_FILE"
}

# -----------------------------------------------------------------------------
# SAFETY CHECK: must be run as root
# /etc/shadow is only readable by root — without this check, hashes will be empty
# -----------------------------------------------------------------------------
if [[ $EUID -ne 0 ]]; then
    echo "[ERROR] This script must be run as root (sudo)."
    echo "Reason: /etc/shadow and other files require root read access."
    exit 1
fi

# -----------------------------------------------------------------------------
# DIRECTORY CHECK
# Make sure the data/ and logs/ directories exist before writing to them
# -----------------------------------------------------------------------------
mkdir -p "$(dirname "$BASELINE_FILE")"
mkdir -p "$(dirname "$LOG_FILE")"

# -----------------------------------------------------------------------------
# BASELINE ALREADY EXISTS — warn the user before overwriting
# This prevents accidental overwrite of a valid baseline with a compromised state
# -----------------------------------------------------------------------------
if [[ -f "$BASELINE_FILE" ]]; then
    echo "[WARNING] A baseline file already exists at: $BASELINE_FILE"
    read -rp "Overwrite it? This will reset your integrity baseline. (yes/no): " confirm
    if [[ "$confirm" != "yes" ]]; then
        echo "[ABORTED] Baseline generation cancelled. Existing baseline preserved."
        exit 0
    fi
fi

# -----------------------------------------------------------------------------
# GENERATE THE BASELINE
# Format of each line in file_baseline.db:
#   filepath|sha256hash|octal_permissions|owner
# Example:
#   /etc/passwd|e3b0c44298fc1c149afb4c8996fb924...|644|root
# -----------------------------------------------------------------------------
echo "[INFO] Generating baseline at: $BASELINE_FILE"
echo "# HIDS File Integrity Baseline" > "$BASELINE_FILE"
echo "# Generated: $(timestamp)" >> "$BASELINE_FILE"
echo "# Format: filepath|sha256hash|permissions|owner" >> "$BASELINE_FILE"
echo "# DO NOT EDIT THIS FILE MANUALLY" >> "$BASELINE_FILE"

skipped=0
recorded=0

for filepath in "${CRITICAL_FILES[@]}"; do

    # Check if the file actually exists before trying to hash it
    if [[ ! -f "$filepath" ]]; then
        log_message "[WARNING]" "Baseline: file not found, skipping: $filepath"
        ((skipped++))
        continue
    fi

    # Compute SHA-256 hash of the file content
    # sha256sum returns: "hash  filename" — awk extracts just the hash
    hash=$(sha256sum "$filepath" 2>/dev/null | awk '{print $1}')

    # Get octal permissions (e.g. 644, 640, 000)
    # stat -c '%a' returns the octal permission bits
    permissions=$(stat -c '%a' "$filepath" 2>/dev/null)

    # Get the file owner name
    owner=$(stat -c '%U' "$filepath" 2>/dev/null)

    # Write one line per file to the baseline
    echo "${filepath}|${hash}|${permissions}|${owner}" >> "$BASELINE_FILE"
    ((recorded++))

done

# -----------------------------------------------------------------------------
# ALSO RECORD THE CURRENT SUID BINARY LIST AS BASELINE
# Any new SUID binary appearing after this baseline = CRITICAL alert
# We store them as a separate section in the same file
# -----------------------------------------------------------------------------
echo "# SUID_BINARIES" >> "$BASELINE_FILE"
echo "# The following SUID binaries were present at baseline time" >> "$BASELINE_FILE"

# find all SUID binaries system-wide, suppress permission errors
find / -perm -4000 -type f 2>/dev/null | sort | while read -r suid_file; do
    echo "SUID|${suid_file}" >> "$BASELINE_FILE"
done

# -----------------------------------------------------------------------------
# SUMMARY
# -----------------------------------------------------------------------------
echo ""
echo "=========================================="
echo "  Baseline generation complete"
echo "  Files recorded : $recorded"
echo "  Files skipped  : $skipped"
echo "  Saved to       : $BASELINE_FILE"
echo "=========================================="
log_message "[INFO]" "Baseline generated: $recorded files recorded, $skipped skipped"
