# Proccess whitelist
# One exact executable path per line

/usr/libexec/at-spi-bus-launcher
/usr/libexec/at-spi2-registryd
/usr/libexec/gvfsd
/usr/libexec/gvfsd-fuse
/usr/libexec/dconf-service
/usr/lib/x86_64-linux-gnu/xfce4/panel/wrapper-2.0
/usr/lib/x86_64-linux-gnu/xfce4/notifyd/xfce4-notifyd
/usr/lib/x86_64-linux-gnu/tumbler-1/tumblerd
/usr/libexec/gvfs-udisks2-volume-monitor
/usr/libexec/gvfs-gphoto2-volume-monitor
/usr/libexec/gvfs-afc-volume-monitor
/usr/libexec/gvfs-goa-volume-monitor
/usr/libexec/gvfs-mtp-volume-monitor
/usr/libexec/gvfsd-metadata
/usr/libexec/gvfsd-trash
/usr/libexec/bluetooth/obexd
/usr/libexec/xdg-desktop-portal
/usr/libexec/xdg-permission-store
/usr/libexec/xdg-document-portal
/usr/libexec/xdg-desktop-portal-gtk
/usr/libexec/polkit-mate-authentication-agent-1
/usr/libexec/geoclue-2.0/demos/agent
